### ISSUE TITLE
Can't read title, titlebox, titlebutton or runes from title archive

### ISSUE THREAD

**Issue by nshusa** [nshusa/rsam#1]

**Comment by nshusa** [comment]
Figured out the issue. RSAM could read them the entire time, the issue with RSAM-GUI was that it failed to decode title.dat.

Title.dat isn't an archive it's an image. The rest are just image archives and decoded the same way all other sprites are.

![1](https://i.imgur.com/NUaFCTY.png)

![2](https://i.imgur.com/ZO7mgqr.png)

**Comment by IanWONeill** [comment]
Interesting.
